"""Aggregated service-layer helpers for Outlook MCP."""

from .email import (
    resolve_mail_item,
    update_cached_email,
    normalize_email_address,
    extract_email_domain,
    derive_sender_email,
    ensure_domain_folder_structure,
    collect_user_addresses,
    mail_item_marked_replied,
    format_email,
    get_emails_from_folder,
    resolve_additional_folders,
    get_all_mail_folders,
    collect_emails_across_folders,
    get_related_conversation_emails,
    email_has_user_reply,
    email_has_user_reply_with_context,
    build_conversation_outline,
    present_email_listing,
    apply_categories_to_item,
    get_email_context,
)
from .calendar import (
    get_all_calendar_folders,
    get_calendar_folder_by_name,
    format_calendar_event,
    get_events_from_folder,
    collect_events_across_calendars,
    present_event_listing,
)
from .system import build_params_payload, get_current_datetime

__all__ = [
    "resolve_mail_item",
    "update_cached_email",
    "normalize_email_address",
    "extract_email_domain",
    "derive_sender_email",
    "ensure_domain_folder_structure",
    "collect_user_addresses",
    "mail_item_marked_replied",
    "format_email",
    "get_emails_from_folder",
    "resolve_additional_folders",
    "get_all_mail_folders",
    "collect_emails_across_folders",
    "get_related_conversation_emails",
    "email_has_user_reply",
    "email_has_user_reply_with_context",
    "build_conversation_outline",
    "present_email_listing",
    "apply_categories_to_item",
    "get_email_context",
    "get_all_calendar_folders",
    "get_calendar_folder_by_name",
    "format_calendar_event",
    "get_events_from_folder",
    "collect_events_across_calendars",
    "present_event_listing",
    "build_params_payload",
    "get_current_datetime",
]
