"""Utility package for Outlook MCP server components."""

from .constants import (
    ATTACHMENT_NAME_PREVIEW_MAX,
    BODY_PREVIEW_MAX_CHARS,
    CONVERSATION_ID_PREVIEW_MAX,
    DEFAULT_CONVERSATION_SAMPLE_LIMIT,
    DEFAULT_DOMAIN_ROOT_NAME,
    DEFAULT_DOMAIN_SUBFOLDERS,
    DEFAULT_MAX_RESULTS,
    DEFAULT_TASK_MAX_RESULTS,
    LAST_VERB_REPLY_CODES,
    LOG_DIR_NAME,
    LOG_FILE_NAME,
    MAX_CONVERSATION_LOOKBACK_DAYS,
    MAX_DAYS,
    MAX_EMAIL_SCAN_PER_FOLDER,
    MAX_EVENT_LOOKAHEAD_DAYS,
    MAX_TASK_DAYS,
    PENDING_SCAN_MULTIPLIER,
    PR_LAST_VERB_EXECUTED,
    PR_LAST_VERB_EXECUTION_TIME,
)
from .logger import logger
from .connection import connect_to_outlook
from .cache import (
    clear_calendar_cache,
    clear_email_cache,
    clear_task_cache,
    email_cache,
    calendar_cache,
    task_cache,
)
from . import utils 

__all__ = [
    "connect_to_outlook",
    "logger",
    "utils",
    "clear_calendar_cache",
    "clear_email_cache",
    "clear_task_cache",
    "email_cache",
    "calendar_cache",
    "task_cache",
    "ATTACHMENT_NAME_PREVIEW_MAX",
    "BODY_PREVIEW_MAX_CHARS",
    "CONVERSATION_ID_PREVIEW_MAX",
    "DEFAULT_CONVERSATION_SAMPLE_LIMIT",
    "DEFAULT_DOMAIN_ROOT_NAME",
    "DEFAULT_DOMAIN_SUBFOLDERS",
    "DEFAULT_MAX_RESULTS",
    "DEFAULT_TASK_MAX_RESULTS",
    "LAST_VERB_REPLY_CODES",
    "LOG_DIR_NAME",
    "LOG_FILE_NAME",
    "MAX_CONVERSATION_LOOKBACK_DAYS",
    "MAX_DAYS",
    "MAX_EMAIL_SCAN_PER_FOLDER",
    "MAX_EVENT_LOOKAHEAD_DAYS",
    "MAX_TASK_DAYS",
    "PENDING_SCAN_MULTIPLIER",
    "PR_LAST_VERB_EXECUTED",
    "PR_LAST_VERB_EXECUTION_TIME",
]
